# Generated by Django 3.1.7 on 2021-06-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_number', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
