# Generated by Django 3.1.7 on 2021-06-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='retweeted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
