# Generated by Django 3.1.7 on 2021-06-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_tweets_retweeted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='retweeted',
            field=models.TextField(),
        ),
    ]
