# Generated by Django 3.1.7 on 2021-06-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_tweets_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='retweeted',
        ),
        migrations.AddField(
            model_name='tweets',
            name='retweet_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
